//
// ********************************************************************
// * License and Disclaimer                                           *
// *                                                                  *
// * The  Geant4 software  is  copyright of the Copyright Holders  of *
// * the Geant4 Collaboration.  It is provided  under  the terms  and *
// * conditions of the Geant4 Software License,  included in the file *
// * LICENSE and available at  http://cern.ch/geant4/license .  These *
// * include a list of copyright holders.                             *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.  Please see the license in the file  LICENSE  and URL above *
// * for the full disclaimer and the limitation of liability.         *
// *                                                                  *
// * This  code  implementation is the result of  the  scientific and *
// * technical work of the GEANT4 collaboration.                      *
// * By using,  copying,  modifying or  distributing the software (or *
// * any work based  on the software)  you  agree  to acknowledge its *
// * use  in  resulting  scientific  publications,  and indicate your *
// * acceptance of all terms of the Geant4 Software license.          *
// ********************************************************************
//

#include "LightTarget.hh"

#include "G4Gamma.hh"
#include "G4PhysicalConstants.hh"
#include "G4PhysicsLinearVector.hh"

////////////////////////////////////////////////////////////////////////////
// Constructor, destructor
LightTarget::LightTarget(G4LogicalVolume* anEnvelope,
                                         G4Material* foilMat,
                                         G4Material* gasMat, G4double a,
                                         G4double b, G4int n,
                                         const G4String& processName)
  : G4InverseCompton(anEnvelope, foilMat, gasMat, a, b, n, processName)
{
  G4cout << "Regular X-ray TR radiator EM process is called" << G4endl;

  // Build energy and angular integral spectra of X-ray TR photons from
  // a radiator

  fAlphaPlate = 10000;
  fAlphaGas   = 1000;
  G4cout << "fAlphaPlate = " << fAlphaPlate << " ; fAlphaGas = " << fAlphaGas
         << G4endl;
}

///////////////////////////////////////////////////////////////////////////
LightTarget::~LightTarget() {}

void LightTarget::ProcessDescription(std::ostream& out) const
{
  out << "Simulation of X-ray transition radiation generated by\n"
         "relativistic charged particles crossing the interface between\n"
         "two materials. Thicknesses of plates and gaps are fixed.\n";
}

///////////////////////////////////////////////////////////////////////////
G4double LightTarget::SpectralXTRdEdx(G4double energy)
{
  // G4double CC = 2.9979 * pow(10, 10);  // cm/s
  // G4double CM = 511000 / (CC * CC);
  // G4double PLANCK = 6.58212 * pow(10, -16); // eV*s
  // G4double LAMBDA = 1.03 * pow(10, -4);  // cm
  // G4cout << "LightTarget::SpectralXTRdEdx(G4double indexD)" << G4endl;
  // G4int index = int(indexD);
  G4double mc2 = 511000.0 * CLHEP::eV;
  G4double r_e = 2.8179403262 * pow(10, -7) * CLHEP::m; // радиус электрона
  G4double gammaCM = 60;
  G4double betaCM = sqrt(1. - 1./gammaCM/gammaCM);

  G4double Ep1 = 2.0 * CLHEP::eV;
  // // G4double Ep1 = PLANCK * 2 * pi * CC / LAMBDA;
  // G4double E_p = PLANCK * 2 * pi * CC / LAMBDA * CLHEP::eV;
  G4double Ep2 = Ep1 * gammaCM * (1. + betaCM);
  G4double E_p = Ep2;
  // G4double fMinEnergyTRCM = E_p/(1. + 2 * E_p / mc2);
  // G4double fMaxEnergyTRCM = E_p;
  // G4PhysicsLinearVector* energyVectorCM =
  //     new G4PhysicsLinearVector(fMinEnergyTRCM, fMaxEnergyTRCM, fBinTR);
  // G4double E_g = energyVectorCM->GetLowEdgeEnergy(index);
  // G4double sz2 = 1. - mc2/E_g + mc2/E_p;
  G4double E_g = (energy/gammaCM + betaCM * mc2)/(1 + betaCM + betaCM*mc2/E_p);


  // E_g = E_g*gammaCM*(1. + betaCM*sz2);

  G4double f = ( (mc2/E_p-mc2/E_g) * (mc2/E_p-mc2/E_g) + 2.0 * (mc2/E_p-mc2/E_g) + E_p/E_g + E_g/E_p ) / (2.0 + 2.0 * E_p/mc2);

  return pi * r_e * r_e * mc2 / (E_p * E_p)  * (2.0 + 2 * E_p / mc2) * f;

}

///////////////////////////////////////////////////////////////////////////
// Approximation for radiator interference factor for the case of
// fully Regular radiator. The plate and gas gap thicknesses are fixed.
// The mean values of the plate and gas gap thicknesses
// are supposed to be about XTR formation zones but much less than
// mean absorption length of XTR photons in corresponding material.

G4double LightTarget::GetStackFactor(G4double energy, G4double gamma,
                                             G4double varAngle)
{
  // some gamma (10000/1000) like algorithm

  G4double result, Za, Zb, Ma, Mb;

  Za = GetPlateFormationZone(energy, gamma, varAngle);
  Zb = GetGasFormationZone(energy, gamma, varAngle);

  Ma = GetPlateLinearPhotoAbs(energy);
  Mb = GetGasLinearPhotoAbs(energy);

  G4complex Ca(1.0 + 0.5 * fPlateThick * Ma / fAlphaPlate,
               fPlateThick / Za / fAlphaPlate);
  G4complex Cb(1.0 + 0.5 * fGasThick * Mb / fAlphaGas,
               fGasThick / Zb / fAlphaGas);

  G4complex Ha = std::pow(Ca, -fAlphaPlate);
  G4complex Hb = std::pow(Cb, -fAlphaGas);
  G4complex H  = Ha * Hb;

  G4complex F1 = (1.0 - Ha) * (1.0 - Hb) / (1.0 - H) * G4double(fPlateNumber);

  G4complex F2 = (1.0 - Ha) * (1.0 - Ha) * Hb / (1.0 - H) / (1.0 - H) *
                 (1.0 - std::pow(H, fPlateNumber));

  G4complex R = (F1 + F2) * OneInterfaceXTRdEdx(energy, gamma, varAngle);

  result = 2.0 * std::real(R);

  return result;
}
